### ISSUE TITLE
Handle maven wrapper download failure without internet

### ISSUE THREAD

**Issue by ystan-** [finos/generator-symphony#199]
### Description of Problem:
In a corporate network environment where an authenticated web proxy is the only way to access the Internet, command line tools often have problems connecting properly. #195 solved the problem of forcing automatic determination of the BDK version, but the next step in the generator fails trying to download the `mvnw` maven wrapper. The project itself is fully generated, so the minimum necessary steps are complete. Developers might also choose not to use the maven wrapper and have a local `mvn` cli already installed and preconfigured to use an internal artifact repository.

### Potential Solutions:
* Handle the download failure by not dumping the stack trace, then noting that it was not possible to download the wrapper
* Check if a local `mvn` exists and use it to continue the `mvn package` run, else just complete the process

**Comment by seimei-san** [comment]
hi Yong Sheng,
This is the error when I ran the latest generator:
----------------
Welcome to Symphony Generator v2.6.0
Application files will be generated in folder: C:\Users\1402374\_projects\_java\samplebot7
______________________________________________________________________________________________________
? Enter your pod host smbcnikko-test.symphony.com
? Enter your bot username kurobot
? Select your type of application Bot Application
? Select your programing language Java
? Select your framework Java (no framework)
? Select your build system Gradle
? Enter your project groupId mybots
? Enter your project artifactId samplebot
? Enter your base package mybots
Failed to fetch latest Java BDK version from Maven Central, 2.6.0 will be used.
The request failed because of: {errno: undefined, code: undefined}
Generating RSA keys...
   create rsa\publickey.pem
   create rsa\privatekey.pem
   create src\main\resources\config.yaml
   create src\main\resources\templates\gif.ftl
   create src\main\resources\templates\welcome.ftl
   create src\main\java\mybots\BotApplication.java
   create src\main\java\mybots\GifFormActivity.java
   create gradlew
   create gradlew.bat
   create gradle\wrapper\gradle-wrapper.jar
   create gradle\wrapper\gradle-wrapper.properties
   create build.gradle
   create .gitignore

No change to package.json was detected. No package manager install will be executed.
Running ./gradlew build in your project
Downloading https://services.gradle.org/distributions/gradle-7.0-bin.zip

Exception in thread "main" java.net.UnknownHostException: services.gradle.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:87)
        at org.gradle.wrapper.Download.download(Download.java:67)
        at org.gradle.wrapper.Install$1.call(Install.java:68)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Error

Command failed with exit code 1: C:\Users\1402374\_projects\_java\samplebot7\gradlew build
